version: '3.3'
services:
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: 'tcgcollections'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./db/seeds.sql:/docker-entrypoint-initdb.d/seeds.sql

  # api:
  #   depends_on:
  #     - db
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: result/latest
  #   command: yarn start

# Names our volume
volumes:
  my-db:
